### ISSUE TITLE
Angular 12 support please?

### ISSUE THREAD

**Issue by Kbdq** [thekip/angular-cc-library#101]
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@">6 <12" from angular-cc-library@2.1.2
npm ERR! node_modules/angular-cc-library
npm ERR!   angular-cc-library@"^2.1.2" from the root project

**Comment by Solat-Ali** [comment]
Yes Please. Now it's a request for Angular 13 support.

**Comment by thekip** [comment]
Angular 12 support
https://github.com/thekip/angular-cc-library/releases/tag/v2.1.3
