### ISSUE TITLE
angular-cc-library is not compatible with angular v16

### ISSUE THREAD

**Issue by wen9218** [thekip/angular-cc-library#121]
Hi, angular-cc-library@3.1.0 is not compatible with Angular v16.
Can you please check?
Thanks

**Comment by born2net** [comment]
Hi and thank you got a great project.
we also can't use the project with Angular 16, any ETA? thank you!
Sean

**Comment by thekip** [comment]
https://github.com/thekip/angular-cc-library/releases/tag/v3.2.0
