### ISSUE TITLE
Cvv & Exp date not validating

### ISSUE THREAD

**Issue by jongbonga** [thekip/angular-cc-library#67]
Cvv & Exp date not validating maxlength. 

<img width="462" alt="Screenshot 2020-04-14 at 14 25 06" src="https://user-images.githubusercontent.com/12111716/79224817-0db0c100-7e5c-11ea-8b84-d9c0253d49bd.png">

**note: using Ionic 5**

**Comment by thekip** [comment]
I don't have experience with Ionic platform and how their control actually works. Cvv & Exp directives  works well in Demo app, could you investigate by yourself what exactly going wrong in Ionic for this directives?

**Comment by thekip** [comment]
Closed due to lack of intertest from the athor
