### ISSUE TITLE
Support Angular 10

### ISSUE THREAD

**Issue by mfluehr** [thekip/angular-cc-library#71]
When using Angular 10, I get these console warnings:
> npm WARN angular-cc-library@2.0.1 requires a peer of @angular/common@>6 <10 but none is installed. You must install peer dependencies yourself.
> npm WARN angular-cc-library@2.0.1 requires a peer of @angular/core@>6 <10 but none is installed. You must install peer dependencies yourself.
> npm WARN angular-cc-library@2.0.1 requires a peer of tslib@^1.10.0 but none is installed. You must install peer dependencies yourself.

The library seems to work fine with Angular 10, despite the warnings.

**Comment by rafaelss95** [comment]
@thekip is there any interest in fix this? Maybe I or any other could help.

**Comment by lviss** [comment]
Yes! I can't install angular-cc-library because I have @angular/common@10.2.3, but the dependency requirement for angular-cc-library is >6 <10

**Comment by mfluehr** [comment]
Angular 11 is out now, by the way. https://blog.angular.io/version-11-of-angular-now-available-74721b7952f7

**Comment by hisham** [comment]
+1

**Comment by thekip** [comment]
Version 2.1.2 just published and supports angular up until 11

**Comment by lviss** [comment]
Awesome! Thank you!
