### ISSUE TITLE
Missing releases !!

### ISSUE THREAD

**Issue by williamdes** [thekip/angular-cc-library#99]
Hi,

I was about to upgrade but could not find any tags on this repository for the last two releases, this is really unsafe.
Could you please push your work for this two releases ?: https://www.npmjs.com/package/angular-cc-library

The linked GitHub repository redirects to here, maybe it should be fixed some way so that NPM detects this repo ?

**Comment by thekip** [comment]
Not sure i get your point. All latest changed already pushed to npm. There were no additional changes.

**Comment by williamdes** [comment]
Check out https://github.com/thekip/angular-cc-library/tags and you will see there is no way to see the sources for the new versions ;)

**Comment by thekip** [comment]
For newer version would do releases and tags, thanks for noting.
